### ISSUE TITLE
θέση σε σχέση με το παράθυρο

### ISSUE THREAD

**Issue by krekon** [krekon/photoStars#11]
Καταγράφει τη θέση σε σχέση με το παράθυρο και όχι με την εικόνα.

**Comment by abaoubas** [comment]
να καταγράφει την θέση της πάνω αριστερής γωνίας του εικονιδίου

να καταγράφει την θέση της σαν αναλογία των διαστάσεων της εικόνας που βλέπει εκείνη την στιγμή ο χρήστης. (αριθμοί απο 0 έως 1). Αν πχ ο χρήστης βλέπει την εικόνα 320χ270 στο κινητό του, και τοποθετήσει το εικονίδιο στο κέντρο πανω, τότε θα αποθηκευθεί 0.5 πλάτος, 0 ύψος

να καταγράφει το μέγεθος του εικονιδίου σαν ποσοστό (0 εως 1) του πλάτους της εικόνας που βλέπει ο χρήστης. πχ αν ο χρήστης βλέπει την εικόνα σε 320χ270, και το εικονίδιο είναι 100 px, τοτε θα αποθηκεύσε 100/320 = 0,3125

Επίσης, θα πρέπει στο finalposition να αποθηκεύονται και οι διαστάσεις τις εικόνας όπως τις έβλεπε ο χρήστης

**Comment by krekon** [comment]
έγινε
